# Generated by Django 3.2.25 on 2024-10-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_ordinal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок картинки'),
        ),
    ]
